config/routes.rb
Rails.application.routes.draw do
  devise_for :regulars, :path => 'traders'
  devise_for :admins
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :asks
  resources :bids
  resources :transactions
  resources :history
  resources :trader
  resources :all_users
  resources :pending_users
  resources :all_transactions
  resources :regulars
  resources :admins
  resources :home
  root to: 'home#index'
  
  get 'stocks/search'
  post 'stocks/search' => 'stocks#create', as: 'stocks_create'
  get 'stocks/show/:id' => 'stocks#show', as: 'stocks_show'
  get 'asks/show/:id' => 'asks#show', as: 'asks_show'
  get 'asks' => 'asks#create', as: 'asks_create'
  get 'bids/show/:id' => 'bids#show', as: 'bids_show'
  get 'bids' => 'bids#create', as: 'bids_create'
  get 'transactions/show/:id' => 'transactions#show', as: 'transactions_show'
  get 'transactions' => 'transactions#create', as: 'transactions_create'

end

app/models/admin.rb
class Admin < User
    validates :name, presence:true     
    validates :email, presence:true         
    validates :surname, presence:true       
    validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask.rb
class Ask < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { other_than: 0 } 
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { other_than: 0 } 
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/owned_stock.rb
class OwnedStock < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { greater_than_or_equal_to: 0 } 
end

app/models/regular.rb
class Regular < User
    validates :name, presence:true     
    validates :email, presence:true         
    validates :surname, presence:true       
    validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/stock.rb
class Stock < ApplicationRecord
    validates :symbol, presence:true       
    validates :name, presence:true       
    validates :current_price, presence:true 
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    has_many :user_transactions
    accepts_nested_attributes_for :user_transactions, allow_destroy: true
    validates :buyer_id, presence:true     
    validates :stock_id, presence:true         
    validates :number_of_stocks, numericality: { other_than: 0 } 
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bids, dependent: :destroy
  has_many :asks, dependent: :destroy
  has_many :owned_stocks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  def admin?
    type == 'admin'
    approved == true
  end
  def regular?
    type == 'regular'
  end
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
    validates :user_id, presence:true     
    validates :stock_id, presence:true         
    validates :number_of_stocks, numericality: { other_than: 0 } 
    validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/all_users_helper.rb
module AllUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    ActionView::Helpers::NumberHelper
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regulars_helper.rb
module RegularsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/trader_helper.rb
module TraderHelper
end

app/views/admins/_adminform.html.erb
<div>
<div class="flex container h-20 bg-blue-900 flex-wrap content-center justify-center text-white">
    <div class="text-center">Update User<br /><%=link_to "Exit", @admin%></div>
</div>
<div class="bg-white pt-10 w-full">
<%= form_with(model: @admin) do |form| %>
  <% if @admin.errors.any? %>
    <div class="form-alert-error"><div style="font-family: 'Varela Round'; padding: 3%;'">Sorry!</div>
      <ul>
        <% @admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <div style="font-family: 'Varela Round'; padding: 3%;">Try again!</div>
    </div> 
  <% end %>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ml-20">
            <%= form.label :email %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 mr-20">
            <%= form.text_field :email %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ml-20">
            <%= form.label :name %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 mr-20">
            <%= form.text_field :name %>
        </div>
    </div>
    
    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ml-20">
            <%= form.label :surname %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 mr-20">
            <%= form.text_field :surname %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4">
            <%= form.label :approved %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ">
            <%= form.check_box :approved %>
        </div>
    </div>

    <div class="flex container flex-wrap content-center justify-center">
        <button class="bg-blue-500 bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-blue-900 font-bold py-2 px-4 rounded mb-10">
            <%= form.submit "Edit User" %>
        </button>
    </div>
<% end %>
</div>
</div>

app/views/admins/edit.html.erb
<div class="w-full h-screen flex justify-center items-center">
<div class="w-full h-screen relative z-0">
<%
user_first = @admin.name
user_sur = @admin.surname
user_first_i = user_first.chars.first
user_sur_i = user_sur.chars.first
join_date_month = @admin.created_at.to_date.strftime("%B")
join_date_year = @admin.created_at.year
%>

<div class="flex container bg-gray-900 w-11/12 my-1.5 p-2.5 mx-auto h-40 text-white flex-wrap content-center">
    <div class="bg-blue-900 mt-2 text-white p-1.5 w-28 h-28 font-bold text-gray-50 rounded-full flex items-center justify-center font-mono text-5xl"><%=user_first_i%><%=user_sur_i%></div>
    <div class="w-6/12 mx-3 p-2"><span class="text-3xl"><%=user_first%> <%=user_sur%> | <%=@admin.email%></span><br /><span class="text-xl">Stocks: <%=@admin.owned_stocks.sum(:number_of_stocks)%> • Balance: USD <%=@admin.balance%></span><br /><span class="text-xm">Joined <%=join_date_month%> <%=join_date_year%></span><br /><span class="text-xs"><%= link_to "Edit", edit_admin_path %> | Admin Trader</span></div>
</div>
<div class="flex container border-4	 p-1.5 border-blue-900 w-11/12 mx-auto overflow-scroll h-60 flex-wrap content-start">
    <% @admin.owned_stocks.each do |ownstock| %>
        <% 
        stock_symbol = Stock.where(id: ownstock.stock_id)[0].symbol
        stock_quantity = ownstock.number_of_stocks
        stock_price = Stock.where(id: ownstock.stock_id)[0].current_price.round(2)
        %>             
        <div class="bg-blue-800 text-white p-1.5 w-24 h-24 mx-2 my-2 font-bold text-gray-50 flex items-center justify-center font-mono"><div class="text-center"><span class="text-xm text-blue-100"><%=stock_symbol%></span><br /><span class="text-xs leading-none"><%=stock_quantity%><br />USD <%=stock_price%></span></div></div>
    <% end %>
</div>

<div class="container w-11/12 mx-auto h-9">
    <div class="flex ...">
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Date</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">With</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Stock</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">No. of Stocks</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Price</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Change in Balance</div>
    </div>      
</div>
<div class="container w-11/12 mx-auto h-36 mx-auto overflow-scroll">
    <% UserTransaction.where(user_id: @admin.id).each do |transaction| %>
        <%
            transaction_specific = Transaction.where(id: transaction.transaction_id)[0]
            transaction_stock = Stock.where(id: transaction.stock_id)[0].name
            transaction_partner_id = 0
            if transaction_specific.seller_id == transaction.user_id
                transaction_partner_id = transaction_specific.buyer_id
            elsif transaction_specific.buyer_id == transaction.user_id
                transaction_partner_id = transaction_specific.seller_id
            end
            transaction_partner = "hello"
            if transaction_partner_id == nil
                transaction_partner = Stock.where(id: transaction.stock_id)[0].symbol
            else
                transaction_partner = User.find(transaction_partner_id).name + " " + User.find(transaction_partner_id).surname
            end
            balance_change = transaction.price * transaction.number_of_stocks
        %>
    <div class="flex ...">
        <div class="bg-blue-800 hover:text-blue-100 hover:underline h-9 text-white p-1.5 w-1/6"><%= transaction.created_at.to_date%> <%= transaction.created_at.in_time_zone('Hong Kong').strftime("%I:%M%p")%></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6"><%= transaction_partner %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6"><%= transaction_stock %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6"><%= transaction.number_of_stocks %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6">USD <%= transaction.price %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6">USD <%= balance_change %></div>
    </div>     
    <% end %> 
</div> 
</div>
<div class="bg-gray-200 bg-opacity-50 absolute inset-0 flex justify-center items-center z-10">
<%= render "adminform" %>
</div>
</div>

app/views/admins/new.html.erb
<div class="flex flex-col h-screen">
<div class="flex w-screen h-20 bg-blue-900 flex-wrap content-center justify-center text-white">
    <div class="text-center">Make New User<br /><%=link_to "Exit", '/all_users'%></div>
</div>
<div class="flex bg-white pt-10 w-screen h-screen flex-wrap content-center justify-center text-white">
<div class="w-1/2">
<%= form_with(model: @admin) do |form| %>
    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ">
            <%= form.label :email %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500">
            <%= form.text_field :email %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ">
            <%= form.label :name %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ">
            <%= form.text_field :name %>
        </div>
    </div>
    
    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ">
            <%= form.label :surname %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ">
            <%= form.text_field :surname %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ">
            <%= form.label :balance %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ">
            <%= form.number_field :balance %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ">
            <%= form.label :password %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ">
            <%= form.password_field :password %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4 ">
            <%= form.label :password_confirmation %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ">
            <%= form.password_field :password_confirmation %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
        <label class="block text-blue-500 font-bold md:text-right mb-1 md:mb-0 pr-4">
            <%= form.label :approved %>
        </label>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 ">
            <%= form.check_box :approved %>
        </div>
    </div>

    <div class="flex container flex-wrap content-center justify-center">
        <button class="bg-blue-500 bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-blue-900 font-bold py-2 px-4 rounded mb-10">
            <%= form.submit "Create User" %>
        </button>
    </div>
<% end %>
</div>
</div>
</div>

app/views/admins/show.html.erb
<%
user_first = @admin.name
user_sur = @admin.surname
user_first_i = user_first.chars.first
user_sur_i = user_sur.chars.first
join_date_month = @admin.created_at.to_date.strftime("%B")
join_date_year = @admin.created_at.year
%>

<div class="flex container bg-gray-900 w-11/12 my-1.5 p-2.5 mx-auto h-40 text-white flex-wrap content-center">
    <div class="bg-blue-900 mt-2 text-white p-1.5 w-28 h-28 font-bold text-gray-50 rounded-full flex items-center justify-center font-mono text-5xl"><%=user_first_i%><%=user_sur_i%></div>
    <div class="w-8/12 mx-3 p-2"><span class="text-3xl"><%=user_first%> <%=user_sur%> | <%=@admin.email%></span><br /><span class="text-xl">Stocks: <%=@admin.owned_stocks.sum(:number_of_stocks)%> • Balance: USD <%=@admin.balance%></span><br /><span class="text-xm">Joined <%=join_date_month%> <%=join_date_year%></span><br /><span class="text-xs"><%= link_to "Edit", edit_admin_path %> | Admin Trader</span></div>
</div>
<div class="flex container border-4	 p-1.5 border-blue-900 w-11/12 mx-auto overflow-scroll h-60 flex-wrap content-start">
    <% @admin.owned_stocks.each do |ownstock| %>
        <% 
        stock_symbol = Stock.where(id: ownstock.stock_id)[0].symbol
        stock_quantity = ownstock.number_of_stocks
        stock_price = Stock.where(id: ownstock.stock_id)[0].current_price.round(2)
        %>             
        <div class="bg-blue-800 text-white p-1.5 w-24 h-24 mx-2 my-2 font-bold text-gray-50 flex items-center justify-center font-mono"><div class="text-center"><span class="text-xm text-blue-100"><%=stock_symbol%></span><br /><span class="text-xs leading-none"><%=stock_quantity%><br />USD <%=stock_price%></span></div></div>
    <% end %>
</div>

<div class="container w-11/12 mx-auto h-9">
    <div class="flex ...">
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Date</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">With</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Stock</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">No. of Stocks</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Price</div>
        <div class="bg-blue-900 h-9 text-white p-1.5 w-1/6">Change in Balance</div>
    </div>      
</div>
<div class="container w-11/12 mx-auto h-36 mx-auto overflow-scroll">
    <% UserTransaction.where(user_id: @admin.id).each do |transaction| %>
        <%
            transaction_specific = Transaction.where(id: transaction.transaction_id)[0]
            transaction_stock = Stock.where(id: transaction.stock_id)[0].name
            transaction_partner_id = 0
            if transaction_specific.seller_id == transaction.user_id
                transaction_partner_id = transaction_specific.buyer_id
            elsif transaction_specific.buyer_id == transaction.user_id
                transaction_partner_id = transaction_specific.seller_id
            end
            transaction_partner = "hello"
            if transaction_partner_id == nil
                transaction_partner = Stock.where(id: transaction.stock_id)[0].symbol
            else
                transaction_partner = User.find(transaction_partner_id).name + " " + User.find(transaction_partner_id).surname
            end
            balance_change = transaction.price * transaction.number_of_stocks
        %>
    <div class="flex ...">
        <div class="bg-blue-800 hover:text-blue-100 hover:underline h-9 text-white p-1.5 w-1/6"><%= transaction.created_at.to_date%> <%= transaction.created_at.in_time_zone('Hong Kong').strftime("%I:%M%p")%></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6"><%= transaction_partner %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6"><%= transaction_stock %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6"><%= transaction.number_of_stocks %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6">USD <%= transaction.price %></div>
        <div class="bg-blue-800 hover:text-blue-100 h-9 text-white p-1.5 w-1/6">USD <%= balance_change %></div>
    </div>     
    <% end %> 
</div> 