config/routes.rb
Rails.application.routes.draw do
  devise_for :regulars, :path => 'traders'
  devise_for :admins
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :asks
  resources :bids
  resources :transactions
  resources :history
  resources :trader
  resources :all_users
  resources :pending_users
  resources :all_transactions
  resources :regulars
  resources :admins
  resources :home
  root to: 'home#index'
  
  get 'stocks/search'
  post 'stocks/search' => 'stocks#create', as: 'stocks_create'
  get 'stocks/show/:id' => 'stocks#show', as: 'stocks_show'
  get 'asks/show/:id' => 'asks#show', as: 'asks_show'
  get 'asks' => 'asks#create', as: 'asks_create'
  get 'bids/show/:id' => 'bids#show', as: 'bids_show'
  get 'bids' => 'bids#create', as: 'bids_create'
  get 'transactions/show/:id' => 'transactions#show', as: 'transactions_show'
  get 'transactions' => 'transactions#create', as: 'transactions_create'

end

app/models/admin.rb
class Admin < User
    validates :name, presence:true     
    validates :email, presence:true         
    validates :surname, presence:true       
    validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask.rb
class Ask < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { other_than: 0 } 
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { other_than: 0 } 
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/owned_stock.rb
class OwnedStock < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { greater_than_or_equal_to: 0 } 
end

app/models/regular.rb
class Regular < User
    validates :name, presence:true     
    validates :email, presence:true         
    validates :surname, presence:true       
    validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/stock.rb
class Stock < ApplicationRecord
    validates :symbol, presence:true       
    validates :name, presence:true       
    validates :current_price, presence:true 
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    has_many :user_transactions
    accepts_nested_attributes_for :user_transactions, allow_destroy: true
    validates :buyer_id, presence:true     
    validates :stock_id, presence:true         
    validates :number_of_stocks, numericality: { other_than: 0 } 
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bids, dependent: :destroy
  has_many :asks, dependent: :destroy
  has_many :owned_stocks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  def admin?
    type == 'admin'
    approved == true
  end
  def regular?
    type == 'regular'
  end
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
    validates :user_id, presence:true     
    validates :stock_id, presence:true         
    validates :number_of_stocks, numericality: { other_than: 0 } 
    validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  def index
      @asks = Ask.all  
  end
  
    def show
      @ask = Ask.find(ask_id)
      @stock = Stock.where(id:@ask.stock_id)
      @list_asks = Ask.where(stock_id:@ask.stock_id).where(sold: false).where.not(user_id: current_user.id)
      @list_bids = Bid.where(stock_id:@ask.stock_id).where(bought: false).where.not(user_id: current_user.id)
      @bid = Bid.all
      @transaction = Transaction.new
      @transaction.user_transactions.build
    end
   
    def create
      @ask = Ask.new(ask_params)
  
      if @ask.save
        redirect_to asks_show_path(@ask)
      else
      end
    end

    def edit
      @ask = Ask.find(ask_id)
      @stock = Stock.where(id:@ask.stock_id)
      @bid = Bid.all
      @list_asks = Ask.where(stock_id:@ask.stock_id).where(sold: false).where.not(user_id: current_user.id)
      @list_bids = Bid.where(stock_id:@ask.stock_id).where(bought: false).where.not(user_id: current_user.id)
      @transaction = Transaction.new
      @transaction.user_transactions.build
    end

    # PATCH/PUT /regulars/1 or /regulars/1.json
    def update
      @ask = Ask.find(ask_id)
        if @ask.update(ask_params)
          redirect_to @ask, notice: "Ask was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
    end

  
    private
      def ask_params
        params.require(:ask).permit(:user_id, :stock_id, :number_of_stocks, :price, :sold)
      end
      
      def ask_id
        params[:id]
      end    

      def transaction_params
        params[:id]
      end
    
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
    def index
        @bids = Bid.all  
    end
    
      def show
        @bid = Bid.find(bid_id)
        @stock = Stock.where(id:@bid.stock_id)
        @ask = Ask.all
        @list_asks = Ask.where(stock_id:@bid.stock_id).where(sold: false).where.not(user_id: current_user.id)
        @list_bids = Bid.where(stock_id:@bid.stock_id).where(bought: false).where.not(user_id: current_user.id)
        @transaction = Transaction.new
        @transaction.user_transactions.build
      end
     
      def create
        @bid = Bid.new(bid_params)
        @user = current_user
        @stock_url = '/stocks/show/' + @bid.stock_id.to_s

        total_price = @bid.number_of_stocks * @bid.price
        if total_price < @user.balance
          @bid.save
          if @bid.save
            redirect_to bids_show_path(@bid)
          end
        else
          redirect_to @stock_url, notice: 'Insufficient balance, please add more cash'
        end
      end

        # GET /regulars/1/edit
      def edit
        @bid = Bid.find(bid_id)
        @stock = Stock.where(id:@bid.stock_id)
        @ask = Ask.all
        @list_asks = Ask.where(stock_id:@bid.stock_id).where(sold: false).where.not(user_id: current_user.id)
        @list_bids = Bid.where(stock_id:@bid.stock_id).where(bought: false).where.not(user_id: current_user.id)
        @transaction = Transaction.new
        @transaction.user_transactions.build
      end

      # PATCH/PUT /regulars/1 or /regulars/1.json
      def update
        @bid = Bid.find(bid_id)
          if @bid.update(bid_params)
            redirect_to @bid, notice: "Bid was successfully updated."
          else
            render :edit, status: :unprocessable_entity
          end
      end
    
      private
        def bid_params
          params.require(:bid).permit(:user_id, :stock_id, :number_of_stocks, :price, :bought, :total_price)
        end
        
        def bid_id
          params[:id]
        end    

        def transaction_params
          params[:id]
        end
      
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :get_api, only: [:show, :search, :index]

    def index
    end

    def search
        @stock = Stock.new
    end

    def get_api
      @client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex_publishable_token,
        secret_token: Rails.application.credentials.iex_secret_token,
        endpoint: 'https://cloud.iexapis.com/v1'
      )
    end

    def stock_params
        params[:symbol]
    end

    def stock_id
        params[:id]
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/all_users_helper.rb
module AllUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    ActionView::Helpers::NumberHelper
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regulars_helper.rb
module RegularsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/trader_helper.rb
module TraderHelper
end

app/views/asks/_editform.html.erb
<div class="bg-green-800 pt-10 w-full">
<%= form_with(model: @ask) do |form| %>
  <% if @ask.errors.any? %>
    <div class="form-alert-error"><div style="font-family: 'Varela Round'; padding: 3%;'">Sorry!</div>
      <ul>
        <% @ask.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <div style="font-family: 'Varela Round'; padding: 3%;">Try again!</div>
    </div> 
  <% end %>

    <div class="md:flex md:items-center mb-6 p-1.5 text-xs ml-10">
        <div class="md:w-full flex">
        <div class="block text-green-100 font-bold md:text-left mb-1 md:mb-0 pr-4">
            <%= form.label :quantity %>
        </div>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 mr-20">
            <%= form.number_field :number_of_stocks %>
        </div>
    </div>

    <div class="md:flex md:items-center mb-6 p-1.5 text-xs ml-10">
        <div class="md:w-full flex">
        <div class="block text-green-100 font-bold md:text-left mb-1 md:mb-0 pr-4">
            <%= form.label :price %>
        </div>
        </div>
        <div class="bg-white appearance-none border-2 border-gray-200 rounded w-72 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500 mr-20">
            <%= form.number_field :price %>
        </div>
    </div>

    <div class="flex container flex-wrap content-center justify-center">
        <button class="bg-green-900 bg-green-500 hover:bg-green-400 focus:shadow-outline focus:outline-none text-green-900 font-bold py-2 px-4 rounded mb-10">
            <%= form.submit "Edit Ask" %>
        </button>
    </div>
<% end %>
</div>
</div>

app/views/asks/_nomatches.html.erb
<div class="bg-green-700 p-1.5 h-72">
Sorry, nobody is bidding at your ask price.<br />(USD <%= @ask.price%>)<br />
<span class="text-xs"><%=link_to "Edit your price.", edit_ask_path%></span>
<br />
<div class="container w-11/12 mx-auto h-9">
<div class="container mt-1 w-full mx-auto overflow-scroll h-9 bg-green-700 border-green-800 border-2">
      <div class="flex">
        <div class="bg-green-800 h-9 hover:text-green-100 text-white pt-2 w-3/6 text-xs">Your Other Asks</div>
        <div class="bg-green-800 h-9 hover:text-green-100 hover:underline text-white pt-2 w-1/6 text-xs">Price</div>
        <div class="bg-green-800 h-9 hover:text-green-100 hover:underline text-white pt-2 w-1/6 text-xs">Qty.</div>
        <div class="bg-green-800 h-9 hover:text-green-100 hover:underline text-white pt-2 w-1/6 text-xs">Match?</div>
      </div>  
  </div>      
</div>
<div class="container mt-1 w-full mx-auto overflow-scroll h-36 bg-green-700 border-green-800 border-2">
  <% Ask.where(user_id: current_user.id).where(sold: false).where(stock_id: @ask.stock_id).each do |ask| %>
    <% 
    check = @bid.where(stock_id: ask.stock_id).where(bought: false).where(price: ask.price).where.not(user_id: current_user.id)[0]
    match_notice = "N/A"
    if check != nil
        match_notice = "MATCH"
    else
    end
    ask_date = ask.created_at.to_date.to_s + " (" + ask.created_at.in_time_zone('Hong Kong').strftime("%I:%M%p").to_s + ")"
    ask_link = '/asks/show/' + ask.id.to_s
    %>
    <div class="flex">
      <div class="bg-green-800 hover:text-green-100 text-white p-1.5 w-3/6 text-xs"><%=link_to ask_date, ask_link%></div>
      <div class="bg-green-800 hover:text-green-100 hover:underline text-white p-1.5 w-1/6 text-xs"><%= ask.price %></div>
      <div class="bg-green-800 hover:text-green-100 hover:underline text-white p-1.5 w-1/6 text-xs"><%= ask.number_of_stocks %></div>
      <div class="bg-green-800 hover:text-green-100 hover:underline text-white p-1.5 w-1/6 text-xs"><%= match_notice %></div>
    </div>      
  <% end %> 
</div>
</div>

app/views/asks/_useraskTransaction.html.erb
<% 
number_stocks_notice = ""
ask_stocks = @bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].number_of_stocks
bid_stocks = @ask.number_of_stocks
number_of_stocks_available = 0
if ask_stocks >= bid_stocks
    number_of_stocks_available = bid_stocks
elsif ask_stocks < bid_stocks
    number_of_stocks_available = ask_stocks
    number_stocks_notice = " (The buyer does not want enough stocks.)"
else
end
%>
<div class="bg-green-800 p-1.5 h-64">
Somebody is bidding at your price!<br />Complete the transaction.<br />
<span class="text-xs">NUMBER OF STOCKS: <%= number_of_stocks_available %><%= number_stocks_notice %></span><br />
<span class="text-xs">PRICE: USD <%=number_with_precision(@bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].price.to_i, precision: 2) %>
</span>
<%= form_with model: @transaction do |f| %>  
    <%= f.hidden_field :buyer_id, value: current_user.id %>
    <%= f.hidden_field :seller_id, value: @bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].user_id %>
    <%= f.hidden_field :stock_id, value: @bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].stock_id %>
    <%= f.hidden_field :price, value: @bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].price %>
    <%= f.hidden_field :number_of_stocks, value: number_of_stocks_available %>

    <%= f.fields_for :user_transactions do |ut_f| %>
      <%= ut_f.hidden_field :user_id, value: current_user.id %>
      <%= ut_f.hidden_field :stock_id, value: @bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].stock_id %>
      <%= ut_f.hidden_field :number_of_stocks, value: number_of_stocks_available %>
      <%= ut_f.hidden_field :price, value: @ask.price %>
    <% end %>
    <%= f.fields_for :user_transactions do |ut_f| %>
        <%= ut_f.hidden_field :user_id, value: @bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].user_id %>
        <%= ut_f.hidden_field :stock_id, value: @bid.where(stock_id: @ask.stock_id).where(price: @ask.price)[0].stock_id %>
        <%= ut_f.hidden_field :number_of_stocks, value: -number_of_stocks_available %>
        <%= ut_f.hidden_field :price, value: @ask.price %>
    <% end %>    
</div>
<div class="bg-green-800 p-1.5 h-8">
    <div class="bg-green-600 rounded-full text-white text-xs text-center">   
    <%= f.submit "Complete Transaction" %>
    </div>
</div>
<% end %>

app/views/asks/edit.html.erb
<% 
stock_link = '/stocks/show/' + @stock[0].id.to_s
%>

<div class="flex w-11/12 p-1 mx-auto h-screen text-white">
  <div class="bg-gray-900 w-4/6 p-2.5 mx-auto h-96 text-white">
    <div class="flex bg-gray-800 w-full p-2.5 mx-auto h-32 text-white">
      <div class="bg-green-900 text-white p-1.5 w-20 h-20 font-bold text-gray-50 rounded-full flex items-center justify-center font-mono text-2xl mt-2"><%=@stock[0].symbol%></div>
      <div class="w-6/12 mx-3 p-2"><span class="text-3xl"><%= @stock[0].name %></span><br /><span class="text-xl">Current Price: USD <%= @stock[0].current_price.round(2) %></span><br /><span class="text-xm">Other Stock Info</span></div>
    </div>
    <div class="flex bg-gray-600 w-full p-2.5 mx-auto h-56 text-white mt-1">
    <div class="w-6/12 p-2 bg-gray-300">
      <div class="container w-11/12 mx-auto h-9">
        <div class="flex mt-1 bg-purple-900 h-9 items-center justify-center">Asks</div>      
      </div>
      <div class="container mt-1 w-11/12 mx-auto overflow-scroll h-36 bg-purple-700 border-purple-800 border-2">
        <% @list_asks.each do |ask| %>
          <div class="flex ...">
            <div class="bg-purple-800 hover:text-purple-100 text-white p-1.5 w-3/5 text-sm"><%= ask.created_at.to_date %> (<%= ask.created_at.in_time_zone('Hong Kong').strftime("%I:%M%p") %>)</div>
            <div class="bg-purple-800 hover:text-purple-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= ask.price %></div>
            <div class="bg-purple-800 hover:text-purple-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= ask.number_of_stocks %></div>
          </div>      
        <% end %> 
      </div>
    </div>
    <div class="w-6/12 p-2 bg-gray-300">
      <div class="container w-11/12 mx-auto h-9">
        <div class="flex mt-1 bg-blue-900 h-9 items-center justify-center">Bids</div>      
      </div>
      <div class="container mt-1 w-11/12 mx-auto overflow-scroll h-36 bg-blue-700 border-blue-800 border-2">
        <% @list_bids.each do |bid| %>
          <div class="flex ...">
            <div class="bg-blue-800 hover:text-blue-100 text-white p-1.5 w-3/5 text-sm"><%= bid.created_at.to_date %> (<%= bid.created_at.in_time_zone('Hong Kong').strftime("%I:%M%p") %>)</div>
            <div class="bg-blue-800 hover:text-blue-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= bid.price %></div>
            <div class="bg-blue-800 hover:text-blue-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= bid.number_of_stocks %></div>
          </div>      
        <% end %> 
      </div>
    </div>
    </div>
  </div>
  <div class="bg-gray-800 w-2/6 p-2.5 mx-auto h-96 text-white text-center">
      <div class="container flex w-11/12 mx-auto overflow-scroll">
        <div class="bg-gray-500 text-white p-1.5 w-4/12 text-xs text-left rounded-t-md"><%= link_to "Bid/Ask", stock_link%></div>
        <div class="bg-gray-700 text-white p-1.5 w-4/12 text-xs text-left rounded-t-md"><%= link_to "Pending Bids", "" %></div>
      </div>
    <div class="bg-green-900 p-1.5">
        <span class="text-xs">Edit your price to get a match.</span>
    </div>
    <%= render 'editform' %>
  </div>
</div>

app/views/asks/show.html.erb
<% 
check = @bid.where(stock_id: @ask.stock_id).where(bought: false).where(price: @ask.price).where.not(user_id: current_user.id)[0]
notice = ""
form = render 'nomatches'
if check != nil
    form = render 'useraskTransaction', transaction: @transaction, ask: @ask, bid: @bid
else
end
stock_link = '/stocks/show/' + @stock[0].id.to_s
%>

<div class="flex w-11/12 p-1 mx-auto h-screen text-white">
  <div class="bg-gray-900 w-4/6 p-2.5 mx-auto h-96 text-white">
    <div class="flex bg-gray-800 w-full p-2.5 mx-auto h-32 text-white">
      <div class="bg-green-900 text-white p-1.5 w-20 h-20 font-bold text-gray-50 rounded-full flex items-center justify-center font-mono text-2xl mt-2"><%=@stock[0].symbol%></div>
      <div class="w-6/12 mx-3 p-2"><span class="text-3xl"><%= @stock[0].name %></span><br /><span class="text-xl">Current Price: USD <%= @stock[0].current_price.round(2) %></span><br /><span class="text-xm">Other Stock Info</span></div>
    </div>
    <div class="flex bg-gray-600 w-full p-2.5 mx-auto h-56 text-white mt-1">
    <div class="w-6/12 p-2 bg-gray-300">
      <div class="container w-11/12 mx-auto h-9">
        <div class="flex mt-1 bg-purple-900 h-9 items-center justify-center">Asks</div>      
      </div>
      <div class="container mt-1 w-11/12 mx-auto overflow-scroll h-36 bg-purple-700 border-purple-800 border-2">
        <% @list_asks.each do |ask| %>
          <div class="flex ...">
            <div class="bg-purple-800 hover:text-purple-100 text-white p-1.5 w-3/5 text-sm"><%= ask.created_at.to_date %> (<%= ask.created_at.in_time_zone('Hong Kong').strftime("%I:%M%p") %>)</div>
            <div class="bg-purple-800 hover:text-purple-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= ask.price %></div>
            <div class="bg-purple-800 hover:text-purple-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= ask.number_of_stocks %></div>
          </div>      
        <% end %> 
      </div>
    </div>
    <div class="w-6/12 p-2 bg-gray-300">
      <div class="container w-11/12 mx-auto h-9">
        <div class="flex mt-1 bg-blue-900 h-9 items-center justify-center">Bids</div>      
      </div>
      <div class="container mt-1 w-11/12 mx-auto overflow-scroll h-36 bg-blue-700 border-blue-800 border-2">
        <% @list_bids.each do |bid| %>
          <div class="flex ...">
            <div class="bg-blue-800 hover:text-blue-100 text-white p-1.5 w-3/5 text-sm"><%= bid.created_at.to_date %> (<%= bid.created_at.in_time_zone('Hong Kong').strftime("%I:%M%p") %>)</div>
            <div class="bg-blue-800 hover:text-blue-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= bid.price %></div>
            <div class="bg-blue-800 hover:text-blue-100 hover:underline text-white p-1.5 w-1/5 text-sm"><%= bid.number_of_stocks %></div>
          </div>      
        <% end %> 
      </div>
    </div>
    </div>
  </div>
  <div class="bg-gray-800 w-2/6 p-2.5 mx-auto h-96 text-white text-center">
      <div class="container flex w-11/12 mx-auto overflow-scroll">
        <div class="bg-gray-500 text-white p-1.5 w-4/12 text-xs text-left rounded-t-md"><%= link_to "Bid/Ask", stock_link%></div>
        <div class="bg-gray-700 text-white p-1.5 w-4/12 text-xs text-left rounded-t-md"><%= link_to "Pending Asks", "" %></div>
      </div>
    <div class="bg-green-900 p-1.5">
        <span class="text-xs">You have placed an ask for <%= @ask.number_of_stocks %> stock/s at USD <%= @ask.price %> each.</span>
    </div>
    <%= form %>
  </div>
</div>