config/routes.rb
Rails.application.routes.draw do
  devise_for :regulars, :path => 'traders'
  devise_for :admins
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :asks
  resources :bids
  resources :transactions
  resources :history
  resources :trader
  resources :all_users
  resources :pending_users
  resources :all_transactions
  resources :regulars
  resources :admins
  resources :home
  root to: 'home#index'
  
  get 'stocks/search'
  post 'stocks/search' => 'stocks#create', as: 'stocks_create'
  get 'stocks/show/:id' => 'stocks#show', as: 'stocks_show'
  get 'asks/show/:id' => 'asks#show', as: 'asks_show'
  get 'asks' => 'asks#create', as: 'asks_create'
  get 'bids/show/:id' => 'bids#show', as: 'bids_show'
  get 'bids' => 'bids#create', as: 'bids_create'
  get 'transactions/show/:id' => 'transactions#show', as: 'transactions_show'
  get 'transactions' => 'transactions#create', as: 'transactions_create'

end

app/models/admin.rb
class Admin < User
    validates :name, presence:true     
    validates :email, presence:true         
    validates :surname, presence:true       
    validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask.rb
class Ask < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { other_than: 0 } 
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { other_than: 0 } 
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/owned_stock.rb
class OwnedStock < ApplicationRecord
  belongs_to :user
  validates :user_id, presence:true     
  validates :stock_id, presence:true         
  validates :number_of_stocks, numericality: { greater_than_or_equal_to: 0 } 
end

app/models/regular.rb
class Regular < User
    validates :name, presence:true     
    validates :email, presence:true         
    validates :surname, presence:true       
    validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/stock.rb
class Stock < ApplicationRecord
    validates :symbol, presence:true       
    validates :name, presence:true       
    validates :current_price, presence:true 
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    has_many :user_transactions
    accepts_nested_attributes_for :user_transactions, allow_destroy: true
    validates :buyer_id, presence:true     
    validates :stock_id, presence:true         
    validates :number_of_stocks, numericality: { other_than: 0 } 
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bids, dependent: :destroy
  has_many :asks, dependent: :destroy
  has_many :owned_stocks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  def admin?
    type == 'admin'
    approved == true
  end
  def regular?
    type == 'regular'
  end
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
    validates :user_id, presence:true     
    validates :stock_id, presence:true         
    validates :number_of_stocks, numericality: { other_than: 0 } 
    validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  def index
      @asks = Ask.all  
  end
  
    def show
      @ask = Ask.find(ask_id)
      @stock = Stock.where(id:@ask.stock_id)
      @list_asks = Ask.where(stock_id:@ask.stock_id).where(sold: false).where.not(user_id: current_user.id)
      @list_bids = Bid.where(stock_id:@ask.stock_id).where(bought: false).where.not(user_id: current_user.id)
      @bid = Bid.all
      @transaction = Transaction.new
      @transaction.user_transactions.build
    end
   
    def create
      @ask = Ask.new(ask_params)
  
      if @ask.save
        redirect_to asks_show_path(@ask)
      else
      end
    end

    def edit
      @ask = Ask.find(ask_id)
      @stock = Stock.where(id:@ask.stock_id)
      @bid = Bid.all
      @list_asks = Ask.where(stock_id:@ask.stock_id).where(sold: false).where.not(user_id: current_user.id)
      @list_bids = Bid.where(stock_id:@ask.stock_id).where(bought: false).where.not(user_id: current_user.id)
      @transaction = Transaction.new
      @transaction.user_transactions.build
    end

    # PATCH/PUT /regulars/1 or /regulars/1.json
    def update
      @ask = Ask.find(ask_id)
        if @ask.update(ask_params)
          redirect_to @ask, notice: "Ask was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
    end

  
    private
      def ask_params
        params.require(:ask).permit(:user_id, :stock_id, :number_of_stocks, :price, :sold)
      end
      
      def ask_id
        params[:id]
      end    

      def transaction_params
        params[:id]
      end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :get_api, only: [:show, :search, :index]

    def index
    end

    def search
        @stock = Stock.new
    end

    def get_api
      @client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex_publishable_token,
        secret_token: Rails.application.credentials.iex_secret_token,
        endpoint: 'https://cloud.iexapis.com/v1'
      )
    end

    def stock_params
        params[:symbol]
    end

    def stock_id
        params[:id]
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/all_users_helper.rb
module AllUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    ActionView::Helpers::NumberHelper
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regulars_helper.rb
module RegularsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/trader_helper.rb
module TraderHelper
end

app/views/home/index.html.erb
<div class="w-full h-full">
<% @list = @client.stock_market_list(:mostactive) %>
<h1 class="font-extrabold text-4xl text-center mt-10">
        CURRENT TOP 10 MOST ACTIVE STOCKS
    </h1>
    <div class="flex flex-wrap flex-row p-2 mt-20 mb-28">
        <% @list.each do | active_stock | %> 
            <% if active_stock.change_percent_s.include?("+") %>
                <div class="bg-gradient-to-r text-white from-green-500 to-green-700 p-2 m-2 max-w-sm mx-auto rounded overflow-hidden shadow-lg hover:shadow-2xl transition duration-500 transform hover:scale-105 cursor-pointer">
            <% elsif active_stock.change_percent_s.include?("-") %>
                <div class="bg-gradient-to-r text-white from-red-500 to-red-800 p-2 m-2 max-w-sm mx-auto rounded overflow-hidden shadow-lg hover:shadow-2xl transition duration-500 transform hover:scale-105 cursor-pointer">
            <% end %>

            <h3 class="p-0 mb-2 text-center flex justify-content-between"> 
                <div class="font-extrabold mr-2"> <%= active_stock.symbol %></div>
                <div class="font-extrabold"> <%= number_to_currency(active_stock.latest_price) %></div> 
            </h3>
                <p class="text-xs"> Volume: <%= number_with_delimiter(active_stock.avg_total_volume, :delimiter => ',') %></p>
                <p class="text-xs"> Change: <%= active_stock.change_percent_s %></p>
            <% if !(active_stock.low.blank?) %>
                <p class="text-xs"> Low: <%= active_stock.low %></p>
                <p class="text-xs"> Open: <%= active_stock.open %></p>
            <% end %>
                <p class="text-xs"> Prev. Close: <%= active_stock.previous_close %></p>
        </div>
    <% end %>
    </div>

    <div class="flex-col items-center justify-center h-2/6 w-screen">
        <div class="flex justify-center self-center">
            <div class="p-5 text-white bg-gradient-to-br from-indigo-300 to-purple-400 mx-auto rounded-2xl w-100">
            <div class="flex flex-col items-center justify-center align-center">
                <div>
                    <a href=<%= stocks_search_path(@stocks_search_path) %> class="flex flex-col justify-center items-center mb-4 p-2 rounded-lg shadow-md h-20 
                    bg-opacity-30 hover:bg-opacity-100
                    bg-blue-900
                    hover:shadow-2xl transition duration-500 transform hover:scale-105 cursor-pointer
                    ">
                        <p class="text-3xl font-bold text-white">Search Stocks</p>
                    </a>

                    <a href=<%= history_index_path %> class="flex flex-col justify-center items-center p-2 rounded-lg shadow-md h-20 
                    bg-opacity-30 hover:bg-opacity-100
                    bg-blue-900
                    hover:shadow-2xl transition duration-500 transform hover:scale-105 cursor-pointer
                    ">
                        <p class="text-3xl font-bold text-white">Transaction History</p>
                    </a>
                </div>
        </div>
    </div>

</div>